---
chain_id: "claim_extraction_test"
name: "Claim Extraction Test Chain"
description: "Simple test chain that only runs claim extraction for testing the implementation"
global_timeout_seconds: 300
parallel_execution: false
stop_on_failure: false
metadata:
  version: "1.0"
  purpose: "testing"
  domain: "general"
  complexity: "low"
  estimated_duration_minutes: 2

passes:
  - type: "claim_extraction"
    name: "Extract Claims"
    pass_id: "extract_claims"
    description: "Extract claims from document using LLM"
    enabled: true
    timeout_seconds: 120
    max_retries: 2
    depends_on: []
    
    parameters:
      model: "claude-3-5-sonnet-20241022"
      prompt_version: "v1"
      max_claims: 30
      min_confidence: 0.5

# Dependencies (none for this simple chain)
dependencies: []